### ISSUE TITLE
More data

### ISSUE THREAD

**Issue by algera** [HackLB/crime-statistics#1]
Not sure when you have your data starting, but we have about a year's worth on our server.  Can I give you SSH access to our db server?

**Comment by rogerhoward** [comment]
@jeffalgera would love it - either email me (rogerhoward@gmail.com) credentials or (if its all the same, probably safer) just send me a database dump. Either way I can pull old records and merge them into this repo. Thanks!

**Comment by algera** [comment]
Cool, sent two JSON dumps your way.  Closing... 🍺
